Development branch
Odongo006/my-professional-portfolio pull request #1
Opened 2022-10-26 20:04 UTC by Odongo006

It was exciting and fun to complete this project, below are the tasks that I completed in this project : -

- Configured linters
- Completed portfolio mobile version header
- Created mobile version branch
- Created pull request

2022-10-26 21:17 UTC, mckent05 requested changes
Hi @Odongo006,

# STATUS: CHANGES REQUIRED ♻️ ♻️  

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!
![almost there](https://user-images.githubusercontent.com/73607512/198139790-bf3a5a3e-9e7d-497b-ac4e-ad7cb18232be.gif)

## Highlights
- All linter checks are passing ✔️ ✔️ 
- Descriptive PR title and summary 👏 
- Your project is looking nice 👍 👍 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-26 21:17 UTC, mckent05 commented on index.html
> +        </div>
- In order to give your page a proper HTML structure it is important that all closing tags have a corresponding opening tag and vice versa. This alsohelps to improve your site's accessibility. I currently cannot see the corresponding opening tag for this div. Please confirm and fix this 👍 👍

2022-10-26 21:17 UTC, mckent05 commented on index.html
> +        </section>
- Good job starting work on your portfolio, your site is gradually coming together, but there are still some differences between this section of your site and the corresponding section in the figma design template.

Your project 👇:
-- Please pay attention to the missing background images on your website, please use the `background-img` property  in CSS to place these images.
<img width="146" alt="henry portfolio" src="https://user-images.githubusercontent.com/73607512/198138339-f1b4ba14-7290-4e50-83b9-b7ebfd007458.PNG">

Design template:
<img width="142" alt="header portfolio 2" src="https://user-images.githubusercontent.com/73607512/198138954-71737c9d-4a50-4f4a-bbf1-48ebde2131e1.PNG">

2022-10-26 21:17 UTC, mckent05 commented on README.md
> +Go to browser and type localhost:8080. This project should run there.
- I'd suggest you add clear steps on how to clone your project locally, this will help make your repo more professional, please fix this 👍 👍

2022-10-26 21:17 UTC, mckent05 commented on README.md
> +LinkedIn: Henry Odongo
- Your social links are currently not working, I'd suggest you fix this to help make your repo look even more professional 👍 👍

2022-10-27 09:03 UTC, jerryowusu requested changes
Hi @Odongo006 :wave: 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![no-we-were-so-close-pauline-turner-brooks](https://user-images.githubusercontent.com/65233860/198241478-78d4dd3e-f7fd-4b52-b658-56d9411760f8.gif)


 ## Highlights
Followed GitHub flow :heavy_check_mark: 
All linters are passing :heavy_check_mark: 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-27 09:03 UTC, jerryowusu commented on README.md
> +Clone the repository into the local computer, and then open the project using web browser.
[OPTIONAL] Kindly provide a link to click in order to clone the repository. This will make it easier for other users to quickly access it.

2022-10-27 10:02 UTC, levy002 requested changes
## Hello @Odongo006   , :wave:
### I'm Levy, your PR reviewer

Good job so far :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)

## Status: REQUIRED CHANGES ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @levy002 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-27 10:02 UTC, levy002 commented on style.css
> +  border-bottom-left-radius: 5rem;
- [ ] As requested by the previous reviewer, kindly align correctly the background image of the headline section in order to meet the provided Figma design. :wink: 

  - ### Your design
    ![image](https://user-images.githubusercontent.com/87197412/198255136-a96c464b-0d11-44e3-a03d-a4b17a4936e1.png)


  - ### Figma design
    ![image](https://user-images.githubusercontent.com/87197412/198255214-ad680de3-7673-4182-b9a8-1faa1671f35f.png)

2022-10-27 10:56 UTC, jerryowusu requested changes
Hi @Odongo006 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![almost-paul-walker](https://user-images.githubusercontent.com/65233860/198266927-aa1560c8-32de-4d4f-85eb-973100fa9bbe.gif)


 ## Highlights
Good commit messages :heavy_check_mark: 
Followed Github flow :heavy_check_mark: 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

- [ ] Kindly provide a detailed description of your project in your readme file. This will make your project look more proffessional and serves as a good pitch to recruiters.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-27 10:56 UTC, jerryowusu commented on style.css
> +  background-image: url(imgs/Header\ bg.svg);
You have been having issues with the background image due to the fact that you are using the image for the desktop version instead of the mobile version. Kindly make sure that you have downloaded the right image from the mobile version of the design and not the desktop version.



Your design            |  The design template
:-------------------------:|:-------------------------:
![Screenshot from 2022-10-27 08-49-22](https://user-images.githubusercontent.com/65233860/198240184-73da7ddd-fd52-4d92-861b-c9d651f17eb7.png)  |  ![Screenshot from 2022-10-27 07-54-19](https://user-images.githubusercontent.com/65233860/198240634-92a197d4-2c02-419a-baba-48a4a7be755f.png)

2022-10-27 14:27 UTC, frank1738 approved these changes
Hi @Odongo006 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media3.giphy.com/media/hryis7A55UXZNCUTNA/giphy.gif"/>

## Highlights

✅ Correct use of Github workflow
✅ No linter error
✅ README is okay
✅ Good PR Description 👍 

## Optional suggestions

N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-27 14:31 UTC, merged