Create form section
Odongo006/my-professional-portfolio pull request #4
Opened 2022-11-02 18:06 UTC by Odongo006

2022-11-03 14:52 UTC, Owusu-Desmond requested changes
Hi @Odongo006 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media2.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.gif"/>

## Highlights
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Great working on the set up the project ✅
📌 Good commit messages ✅
📌 Professional README file ✅

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-03 14:52 UTC, Owusu-Desmond commented on style.css
> +}
- [ ] Please form the project requirements, you should give implement the button interactions (enable, hover, etc.). 
  ![Screenshot from 2022-11-03 14-40-22](https://user-images.githubusercontent.com/92303891/199751450-8232435d-1fec-40ca-90f8-6be3409555f1.png)

You can change the background color, and text color and increase the size a bit on hover. You should follow the [Figma design ](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39%3A122) for the button on hover.

- [ ] Why don't you give your button property of `cursor: pointer` to make a cursor change when it is been hovered?

2022-11-03 14:52 UTC, Owusu-Desmond commented on index.html
> +           </section>
- [ ] It would be better if you use the `footer` tag instead of the `section` tag for semantic reasons since the contact form is at the footer of the page

2022-11-04 10:47 UTC, fobadara approved these changes
Hi @Odongo006, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✅ Linters are passing
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-04 11:04 UTC, merged